//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarGraph.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public int BarId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int Size { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
